# Generated by Django 5.0.2 on 2024-02-24 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_image_alter_user_pub_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 24, 1, 38, 41, 324927, tzinfo=datetime.timezone.utc)),
        ),
    ]
