# Generated by Django 5.0.2 on 2024-02-27 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(null=True, verbose_name='date commented'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 27, 6, 18, 45, 57648, tzinfo=datetime.timezone.utc)),
        ),
    ]
